// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/hephaistos/core/event_sourcing/event_envelope.proto

package event_sourcing

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	AggregateId   string                 `protobuf:"bytes,2,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	TypeName      string                 `protobuf:"bytes,3,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_pkg_hephaistos_core_event_sourcing_event_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hephaistos_core_event_sourcing_event_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_pkg_hephaistos_core_event_sourcing_event_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *EventEnvelope) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventEnvelope) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *EventEnvelope) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *EventEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EventEnvelope) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *EventEnvelope) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_pkg_hephaistos_core_event_sourcing_event_envelope_proto protoreflect.FileDescriptor

const file_pkg_hephaistos_core_event_sourcing_event_envelope_proto_rawDesc = "" +
	"\n" +
	"7pkg/hephaistos/core/event_sourcing/event_envelope.proto\x12\x0eevent_sourcing\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc7\x02\n" +
	"\rEventEnvelope\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12!\n" +
	"\faggregate_id\x18\x02 \x01(\tR\vaggregateId\x12\x1b\n" +
	"\ttype_name\x18\x03 \x01(\tR\btypeName\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12;\n" +
	"\voccurred_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12G\n" +
	"\bmetadata\x18\x06 \x03(\v2+.event_sourcing.EventEnvelope.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B/Z-simplebank/pkg/hephaistos/core/event_sourcingb\x06proto3"

var (
	file_pkg_hephaistos_core_event_sourcing_event_envelope_proto_rawDescOnce sync.Once
	file_pkg_hephaistos_core_event_sourcing_event_envelope_proto_rawDescData []byte
)

func file_pkg_hephaistos_core_event_sourcing_event_envelope_proto_rawDescGZIP() []byte {
	file_pkg_hephaistos_core_event_sourcing_event_envelope_proto_rawDescOnce.Do(func() {
		file_pkg_hephaistos_core_event_sourcing_event_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_hephaistos_core_event_sourcing_event_envelope_proto_rawDesc), len(file_pkg_hephaistos_core_event_sourcing_event_envelope_proto_rawDesc)))
	})
	return file_pkg_hephaistos_core_event_sourcing_event_envelope_proto_rawDescData
}

var file_pkg_hephaistos_core_event_sourcing_event_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_hephaistos_core_event_sourcing_event_envelope_proto_goTypes = []any{
	(*EventEnvelope)(nil),         // 0: event_sourcing.EventEnvelope
	nil,                           // 1: event_sourcing.EventEnvelope.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_pkg_hephaistos_core_event_sourcing_event_envelope_proto_depIdxs = []int32{
	2, // 0: event_sourcing.EventEnvelope.occurred_at:type_name -> google.protobuf.Timestamp
	1, // 1: event_sourcing.EventEnvelope.metadata:type_name -> event_sourcing.EventEnvelope.MetadataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_hephaistos_core_event_sourcing_event_envelope_proto_init() }
func file_pkg_hephaistos_core_event_sourcing_event_envelope_proto_init() {
	if File_pkg_hephaistos_core_event_sourcing_event_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_hephaistos_core_event_sourcing_event_envelope_proto_rawDesc), len(file_pkg_hephaistos_core_event_sourcing_event_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_hephaistos_core_event_sourcing_event_envelope_proto_goTypes,
		DependencyIndexes: file_pkg_hephaistos_core_event_sourcing_event_envelope_proto_depIdxs,
		MessageInfos:      file_pkg_hephaistos_core_event_sourcing_event_envelope_proto_msgTypes,
	}.Build()
	File_pkg_hephaistos_core_event_sourcing_event_envelope_proto = out.File
	file_pkg_hephaistos_core_event_sourcing_event_envelope_proto_goTypes = nil
	file_pkg_hephaistos_core_event_sourcing_event_envelope_proto_depIdxs = nil
}
