// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/domain/events/account_events.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountCreated) Reset() {
	*x = AccountCreated{}
	mi := &file_internal_domain_events_account_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountCreated) ProtoMessage() {}

func (x *AccountCreated) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_events_account_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountCreated.ProtoReflect.Descriptor instead.
func (*AccountCreated) Descriptor() ([]byte, []int) {
	return file_internal_domain_events_account_events_proto_rawDescGZIP(), []int{0}
}

func (x *AccountCreated) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountCreated) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *AccountCreated) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AccountCreated) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type MoneyDeposited struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoneyDeposited) Reset() {
	*x = MoneyDeposited{}
	mi := &file_internal_domain_events_account_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoneyDeposited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoneyDeposited) ProtoMessage() {}

func (x *MoneyDeposited) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_events_account_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoneyDeposited.ProtoReflect.Descriptor instead.
func (*MoneyDeposited) Descriptor() ([]byte, []int) {
	return file_internal_domain_events_account_events_proto_rawDescGZIP(), []int{1}
}

func (x *MoneyDeposited) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *MoneyDeposited) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type MoneyWithdrawn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoneyWithdrawn) Reset() {
	*x = MoneyWithdrawn{}
	mi := &file_internal_domain_events_account_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoneyWithdrawn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoneyWithdrawn) ProtoMessage() {}

func (x *MoneyWithdrawn) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_events_account_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoneyWithdrawn.ProtoReflect.Descriptor instead.
func (*MoneyWithdrawn) Descriptor() ([]byte, []int) {
	return file_internal_domain_events_account_events_proto_rawDescGZIP(), []int{2}
}

func (x *MoneyWithdrawn) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *MoneyWithdrawn) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_internal_domain_events_account_events_proto protoreflect.FileDescriptor

const file_internal_domain_events_account_events_proto_rawDesc = "" +
	"\n" +
	"+internal/domain/events/account_events.proto\x12\x06events\"}\n" +
	"\x0eAccountCreated\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"G\n" +
	"\x0eMoneyDeposited\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"G\n" +
	"\x0eMoneyWithdrawn\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amountB#Z!simplebank/internal/domain/eventsb\x06proto3"

var (
	file_internal_domain_events_account_events_proto_rawDescOnce sync.Once
	file_internal_domain_events_account_events_proto_rawDescData []byte
)

func file_internal_domain_events_account_events_proto_rawDescGZIP() []byte {
	file_internal_domain_events_account_events_proto_rawDescOnce.Do(func() {
		file_internal_domain_events_account_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_domain_events_account_events_proto_rawDesc), len(file_internal_domain_events_account_events_proto_rawDesc)))
	})
	return file_internal_domain_events_account_events_proto_rawDescData
}

var file_internal_domain_events_account_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_domain_events_account_events_proto_goTypes = []any{
	(*AccountCreated)(nil), // 0: events.AccountCreated
	(*MoneyDeposited)(nil), // 1: events.MoneyDeposited
	(*MoneyWithdrawn)(nil), // 2: events.MoneyWithdrawn
}
var file_internal_domain_events_account_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_domain_events_account_events_proto_init() }
func file_internal_domain_events_account_events_proto_init() {
	if File_internal_domain_events_account_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_domain_events_account_events_proto_rawDesc), len(file_internal_domain_events_account_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_domain_events_account_events_proto_goTypes,
		DependencyIndexes: file_internal_domain_events_account_events_proto_depIdxs,
		MessageInfos:      file_internal_domain_events_account_events_proto_msgTypes,
	}.Build()
	File_internal_domain_events_account_events_proto = out.File
	file_internal_domain_events_account_events_proto_goTypes = nil
	file_internal_domain_events_account_events_proto_depIdxs = nil
}
